/**
 * build.js — library build for bs-map-classifier
 *
 * 1. Compiles ESM source → CJS (dist/cjs/*.js) with a nested package.json
 *    { "type": "commonjs" } so Node.js treats the .js files as CJS even
 *    though the root package is "type": "module".
 *
 * 2. Generates dist/embedded.mjs + dist/cjs/embedded.js — standalone files
 *    that contain the ONNX model as base64 so callers need zero extra setup.
 */

import esbuild from 'esbuild';
import { copyFile, readFile, writeFile, mkdir } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));

// ── 0. Sync models from the repo-root training output ─────────────────────────
// Source of truth: <repo-root>/models/onnx/ (written by src/models/export_onnx.py)
// Destination:     js/lib/models/            (committed as a fallback, kept fresh here)

const REPO_ROOT   = resolve(__dirname, '../..');
const MODELS_SRC  = join(REPO_ROOT, 'models', 'onnx');
const MODELS_DEST = join(__dirname, 'models');

for (const file of ['pattern_classifier.onnx', 'pattern_classifier_meta.json']) {
  try {
    await copyFile(join(MODELS_SRC, file), join(MODELS_DEST, file));
    console.log(`  Synced ${file} from models/onnx/`);
  } catch {
    console.log(`  ${file}: using existing copy (models/onnx/ not found or not readable)`);
  }
}

// ── 1. CJS output ──────────────────────────────────────────────────────────────

await mkdir(join(__dirname, 'dist/cjs'), { recursive: true });

// The nested package.json makes Node.js treat *.js files here as CJS,
// overriding the root-level "type": "module".
await writeFile(
  join(__dirname, 'dist/cjs/package.json'),
  JSON.stringify({ type: 'commonjs' }) + '\n',
);

await esbuild.build({
  entryPoints: [
    'src/index.js', 'src/parser.js', 'src/features.js',
    'src/classify.js', 'src/patterns.js',
  ],
  format: 'cjs',
  platform: 'node',
  bundle: false,
  outdir: 'dist/cjs/',
  logLevel: 'info',
});

// ── 2. Embedded model files ────────────────────────────────────────────────────

const modelBytes = await readFile(join(__dirname, 'models/pattern_classifier.onnx'));
const modelB64   = modelBytes.toString('base64');
const modelMeta  = await readFile(join(__dirname, 'models/pattern_classifier_meta.json'), 'utf8');

// Works in both browser (atob) and Node.js (Buffer)
const decodeHelper = `\
function _decode(b64) {
  if (typeof Buffer !== 'undefined') return new Uint8Array(Buffer.from(b64, 'base64')).buffer;
  return Uint8Array.from(atob(b64), c => c.charCodeAt(0)).buffer;
}`;

const embeddedESM = `// Auto-generated by build.js — do not edit.
import { loadClassifierFromBuffers } from '../src/index.js';

${decodeHelper}

const _b64  = ${JSON.stringify(modelB64)};
const _meta = ${modelMeta};

/** Load the classifier with the bundled model — no path or URL needed. */
export async function loadEmbeddedClassifier() {
  return loadClassifierFromBuffers(_decode(_b64), _meta);
}
`;

const embeddedCJS = `// Auto-generated by build.js — do not edit.
'use strict';
const { loadClassifierFromBuffers } = require('./index.js');

${decodeHelper}

const _b64  = ${JSON.stringify(modelB64)};
const _meta = ${modelMeta};

/** Load the classifier with the bundled model — no path or URL needed. */
async function loadEmbeddedClassifier() {
  return loadClassifierFromBuffers(_decode(_b64), _meta);
}

exports.loadEmbeddedClassifier = loadEmbeddedClassifier;
`;

await writeFile(join(__dirname, 'dist/embedded.mjs'), embeddedESM);
await writeFile(join(__dirname, 'dist/cjs/embedded.js'), embeddedCJS);

console.log(
  `✓ Built CJS + embedded model ` +
  `(${(modelBytes.length / 1024).toFixed(0)} KB → ${(modelB64.length / 1024).toFixed(0)} KB base64)`,
);
